name: Node.js Staging Deployment 

on:
  push:
    branches: [ "staging" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
            
    - name: Build  App
      run: |
        cp -f staging-env .env
        npm install
        npm run build
        rm -rf ./node_modules
        rm -rf .git
    
    - name: Deploy files to S3 Bucket
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws --region=us-east-1 s3 sync --delete build s3://dev.branchdevs.com

    - name: Purge Cloudfront Cache
      uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: ENY30QIZ1QJK3
            